version: "3"
services:
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 220513
            MYSQL_DATABASE: dev
            MYSQL_USER: root
            MYSQL_PASSWORD: admin
        volumes:
            - "data:/var/lib/mysql"
volumes:
    data: