version: "3"
services:
    asterisk:
        image: eyeruleall/asterisk17
        container_name:
            "lab-asterisk"
        ports:
            - "5060:5061"
        restart: always
volumes:
    data: