version: "3"
services:
    asterisk:
        image: andrius/asterisk:latest
        container_name:
            "lab-asterisk"
        ports:
            - "5060:5060"
        restart: always
volumes:
    data: