version: "3"
services:
    opensips:
        build: .
        container_name:
            "Opensips32Lab"
        ports:
            - "5060:5061"
        restart: always
    
        environment:
            DEBIAN_FRONTEND: noninteractive
        volumes:
            - "data:/etc/opensips"
          
volumes:
    data: