version: '3'
services:
  redis:
    image: redis
    container_name: RedisLab
    networks:
      database_network:
        ipv4_address: 10.8.0.4
  ports:
    - '6379:6379'
  restart: always
  command: redis-server --requirepass CAllBoxSbc!
volumes:
  data: null
networks:
  database_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
        - gateway: 10.6.0.1
